name:                deep-embedding-kuifje
version:             0.1.0.0
github:              "githubuser/deep-embedding-kuifje"
license:             BSD3
author:              "Jef Versavel"
maintainer:          "jef.versavel@student.kuleuven.be"
copyright:           "2020 Jef Versavel"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/deep-embedding-kuifje#readme>

dependencies:
- base >= 4.7 && < 5
- kuifje
- containers
- mtl
- lens
- bytestring
- cereal
- boxes
- template-haskell

library:
  source-dirs: src
